# Generated by Django 4.0.4 on 2022-06-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
