# Generated by Django 4.0.4 on 2022-06-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_status_wishlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='status',
        ),
    ]
