# Generated by Django 4.0.4 on 2022-06-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_wishlist_total_items_wishlist_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wishlist.status'),
        ),
    ]
